### ISSUE TITLE
Chapter 5: Won't accept correct answer 

### ISSUE THREAD

**Issue by applezoid** [buidl-labs/crypto-code-school-inside-tezos#107] opened 2020-05-21 20:36 UTC
Chapter 5 will not accept the correct answer despite it being exactly as appears in the show answer drop down. 
![Screen Shot 2020-05-21 at 4 01 27 PM](https://user-images.githubusercontent.com/29128311/82603720-c7483380-9b78-11ea-9cf1-3b65e1fe3c8e.png)

**Comment by prastut** [comment] 2020-05-22 03:58
Hi @applezoid , thank you filing for this issue. We will get this fixed asap!

**Comment by prastut** [comment] 2020-05-22 04:14
@bhaskarSingh this is strange. The answer key in the above screenshot lacks indentation and that I think is the root cause of the bug. 

I checked my editor and it seems I get to see both cases O.o 



My Chapter 5 screenshot:

Case 1: No indentation in both user's submission and answer key
![image](https://user-images.githubusercontent.com/10279686/82629879-a3373180-9c0e-11ea-9d4c-0ad09a5e1935.png)

Case 2: If I reset the editor I get to see this: 
![image](https://user-images.githubusercontent.com/10279686/82630633-e09cbe80-9c10-11ea-9521-64845f568dbf.png)

**Comment by bhaskarSingh** [comment] 2020-05-22 15:44
@applezoid  issue has been fixed now, could you please check it again.

**Comment by prastut** [comment] 2020-05-27 07:59
Closing as this issue has been solved now.

**Closed by prastut** 2020-05-27 07:59 UTC
Labels: Priority: Critical, bug
